### ISSUE TITLE
Parsing error: config file must be in JSON format

### ISSUE THREAD

**Issue by protist** [a-sk/node-imapnotify#1]
I can't seem to get node-imapnotify to work. I've installed nodejs-imapnotify-git on Arch from the AUR, then copied the node-module config file from the "myconfig.js" example. I changed text between `<>` and `~/getpass.sh`. However, I get the following error when trying to run it.

```
$ imapnotify -c ~/.config/imapnotify.js 
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":30266,"level":50,"msg":"Parsing error: config file must be in JSON format","time":"2015-09-30T00:35:02.425Z","v":0}
```

**Comment by a-sk** [comment]
Hey, 
could you please tell me what version of node.js do you use.
And can you run node.js prompt and require() your config.

**Comment by protist** [comment]
I'm using nodejs 4.1.1. I'm afraid I know absolutely nothing about Javascript, so I'm not sure how to do that. Could you please provide step-by-step instructions, and I'll attempt to follow them. Cheers.

**Comment by a-sk** [comment]
Sure.
1. run `node` in your terminal
2. require (import) your config by full path:

``` javascript
require('/full/path/to/your/config')
```
1. see if there is any errors and post it here.

**Comment by protist** [comment]
Thank you for the advice… ahhhh ok. As I mentioned, I know nothing about Javascript, so I copied the example verbatim. I didn't quote the part in `exports.boxes = [ <boxes> ];`. Once I put that in quotes, it worked. For consistency, perhaps the example should say `exports.boxes = [ "<boxes>" ];`

However, now I'm getting the following error.

```
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":30,"box":"INBOX","msg":"Connected to server","time":"2015-10-02T12:00:52.319Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":30,"box":"INBOX","msg":"Selecting box","time":"2015-10-02T12:00:52.322Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":30,"box":"INBOX","msg":"Connection ended","time":"2015-10-02T12:01:02.110Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":50,"box":"INBOX","msg":"Error registered","time":"2015-10-02T12:01:02.176Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":50,"box":"INBOX","msg":"{ [Error: connect ECONNREFUSED 103.241.1.188:993]\n  code: 'ECONNREFUSED',\n  errno: 'ECONNREFUSED',\n  syscall: 'connect',\n  address: '103.241.1.188',\n  port: 993,\n  source: 'socket' }","time":"2015-10-02T12:01:02.178Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2015-10-02T12:01:02.178Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":50,"box":"INBOX","msg":"Error registered","time":"2015-10-02T12:01:02.238Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":50,"box":"INBOX","msg":"{ [Error: connect ECONNREFUSED 103.241.1.188:993]\n  code: 'ECONNREFUSED',\n  errno: 'ECONNREFUSED',\n  syscall: 'connect',\n  address: '103.241.1.188',\n  port: 993,\n  source: 'socket' }","time":"2015-10-02T12:01:02.239Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":11014,"level":30,"box":"INBOX","msg":"Scheduling restart in 3000","time":"2015-10-02T12:01:02.239Z","v":0}
```

I presume that there's some other kind of error in my config?

**Comment by a-sk** [comment]
- the part about boxes should be a list of boxes to monitor, like for example ['INBOX', 'lists/vim-dev'] etc.
- try to disable tls check by adding the following line to your config:

``` javascript
  exports.tlsOptions = { "rejectUnauthorized": false };
```
- and also check if you can connect to port 993 and ip 103.241.1.188

**Comment by protist** [comment]
Thanks again for the help.

> try to disable tls check by adding the following line to your config

Yes, that was already in there. (I'm using exactly the same config as your `myconfig.js` example, only changing the sections as per the first post.)

> and also check if you can connect to port 993 and ip 103.241.1.188/

I specified a domain name in the config file, so imapnotify seems to be automatically converting it to an IP address. I can ping the address, but I'm not sure how to check the port. In any case, I'm using the exact same configuration as my Thunderbird instance (same domain name, and port number), which works fine. I'm not 100% sure what the `tlsOptions` mean, but in my Thunderbird config, it says
- Connection security: `SSL/TLS`
- Authentication method: `Normal password`

**Comment by protist** [comment]
Ahhh… apologies. It does seem to be working now. Perhaps the errors were after suspending the system. Thank you for the help, and the excellent program! (I'm migrating to mutt, and this will be most helpful!)

**Comment by a-sk** [comment]
I'm glad that it is working now.
Happy mutting :+1:
