### ISSUE TITLE
Cannot get systemd service to work with config.js and encrypted password

### ISSUE THREAD

**Issue by protist** [a-sk/node-imapnotify#2]
Hello again,

imapnotify has been working very well for me when manually starting it from the command line as. However, I've been struggling to get the bundled systemd service working (from the Arch AUR package). I edited the file at `/usr/lib/systemd/system/imapnotify@.service` as follows:

```
/usr/lib/systemd/system$ diff -aur imapnotify@.service{.orig,}
--- imapnotify@.service.orig    2015-09-29 22:18:10.000000000 +1000
+++ imapnotify@.service 2015-10-06 15:30:10.831899633 +1100
@@ -3,9 +3,9 @@
 After=network.target

 [Service]
-User=username
+User=protist
 Type=simple
-ExecStart=/usr/bin/imapnotify -c ~/.config/imap_inotify/%I.json
+ExecStart=/usr/bin/imapnotify -c /home/protist/.config/imapnotify/%I.js
 Restart=on-failure
 RestartSec=20
```

After running `sudo systemctl start imapnotify@accountA`, the service starts fine. However, I get `Authentication failed` errors. I have stores the password in the python-accessible gnome keyring, as per suggestions in the Arch [wiki](https://wiki.archlinux.org/index.php/OfflineIMAP#python2-keyring) for offlineimap. Hence, there is the following line in `/home/protist/.config/imapnotify/accountA.js`.

```
exports.password = getStdout('python2 -c \'import keyring; print keyring.get_password("imapnotify","accountA@foo.com")\'');
```

This works fine when launching imapnotify from the command line. When it fails from systemd, I wondered if perhaps the sudo process didn't have the correct environment variables. I tried making the systemd service a user service. (IMO if this worked it would be the "proper" way to do it.) I copied the service file to `/usr/lib/systemd/user/imapnotify@.service` and removed the line with `User=username`. I then ran `systemctl --user start imapnotify@accountA`. This time, it failed with

```
imapnotify@admin.service: Failed at step GROUP spawning /usr/bin/imapnotify: Operation not permitted
```

Is there a way to use encrypted passwords with the systemd service?

**Comment by protist** [comment]
Ahhhh… okay it's working now. I ran several iterations of the service file, but I never actually tested the last suggestion correctly!

It works fine if you set it up as a user service, _and_ remove the line with `User=username`. Personally, I think it makes more sense to install the systemd service to the user directory at `/usr/lib/systemd/user`. Firstly, this would allow normal users to set up the service. Secondly, users wouldn't have to modify the file, specifically the `User` line. Thirdly, the python-keyring would work!

Are you the package maintainer? Are these changes that you'd agree with? Also, there is (presumably) a slight typo in `ExecStart=/usr/bin/imapnotify -c ~/.config/imap_inotify/%I.json`. I would have expected the path to include `imapnotify` instead of `imap_inotify`, without the `_i`, to be consistent with the repository name.

In any case, it's working fantastically now! Thank you very much for the great program!

**Comment by a-sk** [comment]
I'm on mac now, so I'm no longer the package maintainer.
As you can [see](https://aur.archlinux.org/packages/nodejs-imapnotify) **yourealwaysbe** is the current maintainer.
Changes seem reasonable, so you can contact him and I'm sure, he will be glad to fix the service file.

**Comment by protist** [comment]
Thank you again.
