### ISSUE TITLE
Lower timeout value after resuming from suspend

### ISSUE THREAD

**Issue by protist** [a-sk/node-imapnotify#3]
I've noticed that when I resume from suspend, imapnotify takes a variable amount of time to connect. Sometimes it's less than a minute. However, today it took 15 minutes. I was wondering if it would be possible to reduce the timeout value? Here are some potentially relevant entries from systemd. (I resumed from suspend at 13:07:21)

```
$ systemctl status --user imapnotify@foo.js.service
May 06 13:21:20 protist-XPS-17 imapnotify[628]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":628,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-05-06T03:21:20.433Z","v":0}
May 06 13:21:20 protist-XPS-17 imapnotify[628]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":628,"level":50,"box":"INBOX","msg":"{ Error: read ETIMEDOUT\n    at exports._errnoException (util.js:896:11)\n   
May 06 13:21:20 protist-XPS-17 imapnotify[628]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":628,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2016-05-06T03:21:20.433Z","v":0}
May 06 13:21:21 protist-XPS-17 imapnotify[628]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":628,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-05-06T03:21:21.033Z","v":0}
May 06 13:21:21 protist-XPS-17 imapnotify[628]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":628,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-05-06T03:21:21.033Z","v":0}
```

**Comment by a-sk** [comment]
Hi,
try to add this snippet to [that](https://github.com/a-sk/node-imapnotify/blob/master/bin/imapnotify#L125) line on your machine and see if it helps?

``` js
    socketTimeout: 10000,
    keepalive: {
      idleInterval: 10000,
      interval: 10000
    }
```

**Comment by protist** [comment]
Thanks. Do you mean to add that code _after_ that line? It's a little hard for me to test, because this delay length is so intermittent. I specifically looked at it again later today, and it took "only" 5 minutes that time. I'll test it over the next few days. What kind of delay are you expecting with this change?

**Comment by a-sk** [comment]
Delay should be 10 to 20 seconds.
The code should look like this:

``` js
var connection = new Imap({
    user: self.config.username,
    password: self.config.password,
    host: self.config.host,
    port: self.config.port,
    tls: self.config.tls || true,
    debug: debug ? debug : noop,
    tlsOptions: self.config.tlsOptions,
    socketTimeout: 10000,
    keepalive: {
      idleInterval: 10000,
      interval: 10000
    }
  });
```

**Comment by protist** [comment]
Thanks again. I'll report back in a few days as to how it is working.

**Comment by protist** [comment]
Hmmm… actually, I can't get the systemd unit to start any more, after I make that modification.

```
$ systemctl restart --user imapnotify@main.js.service
$ systemctl status --user imapnotify@main.js.service
● imapnotify@main.js.service - Execute scripts on new messages using IDLE imap command
   Loaded: loaded (/usr/lib/systemd/user/imapnotify@.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2016-05-06 22:34:24 AEST; 1s ago
  Process: 6385 ExecStart=/usr/bin/imapnotify -c %h/.config/imapnotify/%I (code=exited, status=1/FAILURE
 Main PID: 6385 (code=exited, status=1/FAILURE)

May 06 22:34:24 protist-XPS-17 systemd[618]: imapnotify@main.js.service: Unit entered failed state.
May 06 22:34:24 protist-XPS-17 systemd[618]: imapnotify@main.js.service: Failed with result 'exit-code'.
```

I tried reverting the change, and it starts again. (I tried applying the change again too, and it again failed.)

I tried to run it manually, and it failed as follows.

```
$ imapnotify -h
/usr/lib/node_modules/imapnotify/bin/imapnotify:126
    socketTimeout: 10000,
    ^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

**Comment by a-sk** [comment]
I think you forgot a comma after `tlsOptions: self.config.tlsOptions` line

**Comment by protist** [comment]
Ah yes, true. Thanks for the catch.

**Comment by protist** [comment]
It didn't seem to work for the last two times. After the last two resumes it took 15 and 16 minutes to restart the systemd process.

**Comment by a-sk** [comment]
Can you show logs after you resumed?

**Comment by protist** [comment]
Sure, although it doesn't look much different to before.

```
May 07 20:19:32 protist-XPS-17 imapnotify[28002]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":28002,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-05-07T10:19:32.014Z","v":0}
May 07 20:19:32 protist-XPS-17 imapnotify[28002]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":28002,"level":50,"box":"INBOX","msg":"{ Error: read ETIMEDOUT\n    at exports._errnoException (util.js:949:11)\
May 07 20:19:32 protist-XPS-17 imapnotify[28002]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":28002,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2016-05-07T10:19:32.015Z","v":0}
May 07 20:19:32 protist-XPS-17 imapnotify[28002]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":28002,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-05-07T10:19:32.585Z","v":0}
May 07 20:19:32 protist-XPS-17 imapnotify[28002]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":28002,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-05-07T10:19:32.586Z","v":0}
```

**Comment by a-sk** [comment]
Maybe you can just restart `imapnotify` service after resume using `systemd`.
You can place a special script in `/usr/lib/systemd/system-sleep/` folder which will be executed before and after suspend.
You can read about it [here](https://www.freedesktop.org/software/systemd/man/systemd-suspend.service.html)

**Comment by protist** [comment]
Thanks. I've tried a two options, but neither seems to work.

Firstly, I took your advice and created `/usr/lib/systemd/system-sleep/restart_imapnotify` as follows.

```
#!/bin/sh
case $1/$2 in
  post/*)
    for i in account1 account2 account3; do
      sudo -u protist systemctl restart --user imapnotify@$i.js.service
    done
    ;;
esac
```

After resuming, according to `sudo journalctl`, they should have run.

```
May 09 15:55:27 protist-XPS-17 sudo[3699]:     root : TTY=unknown ; PWD=/ ; USER=protist ; COMMAND=/usr/sbin/systemctl restart --user imapnotify@account1.js.service
...
May 09 15:55:27 protist-XPS-17 sudo[3701]:     root : TTY=unknown ; PWD=/ ; USER=protist ; COMMAND=/usr/sbin/systemctl restart --user imapnotify@account2.js.service
...
May 09 15:55:27 protist-XPS-17 sudo[3703]:     root : TTY=unknown ; PWD=/ ; USER=protist ; COMMAND=/usr/sbin/systemctl restart --user imapnotify@account3.js.service
```

However, checking the individual services (with `systemctl status --user imapnotify@account1.js.service`) show that they have not restarted. I think I've struggled with this kind of thing before. I've tried placing (user) scripts in `~/.config/systemd/user` instead, but they need to rely on system-level resume scripts, so it's not simple to solve.

---

FWIW I also tried an alternative method. I created the following script in `/home/protist/.local/bin/restart_imapnotify`

```
#!/bin/sh
for i in account1 account2 account3; do
  systemctl restart --user imapnotify@$i.js.service
done
```

Running this script works by itself. I tried to call it with a script at `/etc/systemd/system/restart_imapnotify.service`

```
[Unit]
Description=Restart imapnotify on resume
After=suspend.target

[Service]
User=protist
Type=simple
ExecStart=/home/protist/.local/bin/restart_imapnotify

[Install]
WantedBy=suspend.target
```

However, testing this with `sudo systemctl start restart_imapnotify.service` fails. From `systemctl status restart_imapnotify.service`:

```
May 09 16:06:38 protist-XPS-17 restart_imapnotify[9354]: Failed to connect to bus: No such file or directory
May 09 16:06:38 protist-XPS-17 restart_imapnotify[9354]: Failed to connect to bus: No such file or directory
May 09 16:06:38 protist-XPS-17 restart_imapnotify[9354]: Failed to connect to bus: No such file or directory
```

**Comment by a-sk** [comment]
Could you try to make `restart_imapnotify` service run under your user, not root.
Like it's done [here].(https://wiki.archlinux.org/index.php/Power_management#Suspend.2Fresume_service_files)

**Comment by protist** [comment]
I just tried this, but it also failed. I suspect because it's basically the same as my second attempt above. The service is not running "under my user", really. The `@` symbol just allows multiple versions of the service to run. When I run `sudo systemctl start restart_imapnotify@protist`, the part after the `@` is substituted for `$I` in the script. In previous script above, I had simply hard-coded that value instead.

OTOH, if I create the service file in `~/.config/systemd/user`, and run it with `systemctl --user start restart_imapnotify` instead, it _does_ work this time. However, after enabling it, it still doesn't trigger on resume. To summarise, it seems that it needs to be `--user` for the bus, but [apparently](https://unix.stackexchange.com/questions/149959/how-to-run-systemd-user-service-to-trigger-on-sleep-aka-suspend-hibernate), user units can't hook into the suspend/resume triggers. From the link above, there are two possible solutions, but both seem fairly suboptimal.

**Comment by protist** [comment]
So I tested the (second) `xss-lock` workaround. It _does_ work, but I think it's suboptimal. I used the `restart_imapnotify` script from my [previous](https://github.com/a-sk/node-imapnotify/issues/3#issuecomment-2177846090) post. I then ran `xss-lock -- restart_imapnotify &`, and suspended. When I resumed, I could see that the systemd services had restarted.

I have a few problems with this approach.
- This presumably runs when I suspend, not when I resume. Hence, if my computer was suspended for a reasonable length of time, presumably imapnotify's would have restarted a long time before my computer actually resumes. I'm not sure if there is some kind of server timeout involved, and if this would be a problem.
- If I left my laptop awake, but my network dropped out, then this hook wouldn't trigger when I was back in network range. This workaround doesn't seem to cover this case.
- It doesn't really integrate with imapnotify natively. It's quite fiddly for users to set up.

Having said that, I'm not sure what other options are available.

**Comment by protist** [comment]
Ah, so I suspended, then resumed ~45 minutes later. This was the systemd output.

```
May 10 16:47:42 protist-XPS-17 systemd[648]: Started Execute scripts on new messages using IDLE imap command.
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-05-10T07:30:00.644Z","v":0}
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":50,"box":"INBOX","msg":"{ Error: getaddrinfo ENOTFOUND mail.foo.com.au mail.foo.com
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2016-05-10T07:30:00.663Z","v":0}
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-05-10T07:30:00.667Z","v":0}
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":50,"box":"INBOX","msg":"{ Error: getaddrinfo ENOTFOUND mail.foo.com.au mail.foo.com
May 10 17:30:00 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":30,"box":"INBOX","msg":"Scheduling restart in 3000","time":"2016-05-10T07:30:00.667Z","v":0}
May 10 17:30:04 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-05-10T07:30:04.537Z","v":0}
May 10 17:30:04 protist-XPS-17 imapnotify[2859]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":2859,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-05-10T07:30:04.537Z","v":0}
```

I also tested another time and after waiting 3000 (milliseconds?) and failing, it waited another 6000. I'm not sure how imapnotify is coded, but as long as it doesn't extend this waiting time too long, this should be okay. Unfortunately, this potentially fixes the first problem, but not the second two.

**Comment by a-sk** [comment]
You can see timeouts [here](https://github.com/a-sk/node-imapnotify/blob/master/bin/imapnotify#L86).
Right now it tries to reconnect immediately, then in 3 seconds then in 6 seconds and then it throws an error and systemd should restart it. 

> If I left my laptop awake, but my network dropped out, then this hook wouldn't trigger when I was back in network range. This workaround doesn't seem to cover this case.

This should be fixed by lowering timeouts of sending `IDLE` or `NOOP` commands. (my first suggestion).
I will try to test those timeouts once again.

**Comment by protist** [comment]
Thanks for the comments and the continued work on this. I really appreciate it.
