### ISSUE TITLE
installing process & configuration

### ISSUE THREAD

**Issue by seblemaguer** [a-sk/node-imapnotify#4]
Hello,

my question might be completely stupid but I have installed npm and node from git which leads to these versions : 

```
➔ node -v    
v7.0.0-pre

~ 
➔ npm -v
3.10.5
```

then I installed the package using the command

``` sh
npm install -g imapnotify
```

and finally tried to use the command using this (I obfuscated my machine name on purpose)

``` sh
~ 
➔ imapnotify -c test.js
{"name":"imap_inotify","hostname":"**********","pid":5206,"level":50,"msg":"Parsing error: config file must be in JSON format","time":"2016-07-07T15:35:40.623Z","v":0}
```

test.js is formatted like that

``` js
var child_process = require('child_process');

function getStdout(cmd) {
    var stdout = child_process.execSync(cmd);
    return stdout.toString().trim();
}

exports.host = "imap.gmail.com";
exports.port = 993;
exports.tls = true;
exports.tlsOptions = { "rejectUnauthorized": false };
exports.username = "******@gmail.com";
exports.password = getStdout("python3 ~/.get_passwd.py 'imap.gmail.com' '*******@gmail.com'");
exports.onNewMail = "/usr/bin/mbsync -a";
exports.onNewMailPost = "echo 'new mail in %s' > ~/tmp.yahoo";
exports.boxes = [ "INBOX" ];
```

so nothing really different from the proposed configuration file. Do you have an idea in which direction should I watch to find what is going wrong ?

Thanks a lot

**Comment by a-sk** [comment]
Hello!

Can you try to run your config file, like `node test.js` and show the output?

**Comment by seblemaguer** [comment]
it doesn't give me anything

**Comment by a-sk** [comment]
I made errors more descriptive: f5cf85d24483119e005c88371939bbdd91c4bb5f
Please update and run `imapnotify -c test.js` again.

**Comment by seblemaguer** [comment]
Hello,

sorry for the delay, here is the result : 

``` sh
➔ imapnotify -c test.js                                                    
{"name":"imap_inotify","hostname":"**********,"pid":25451,"level":50,"msg":"Parsing error: config file must be in JSON format or a valid JS module: Error: Cannot find module 'test.js'","time":"2016-07-12T11:37:39.072Z","v":0}
```

and test.js is on the current path

**Comment by seblemaguer** [comment]
ok apparently you need to have the parent directory of "test.js" (so $PWD in my case) in $NODE_PATH

**Comment by a-sk** [comment]
Or you can pass a full path to the config file, e.g.: `~/test.js`, seems to work this way, I will update the readme.

**Comment by seblemaguer** [comment]
yup right :) Thanks a lot
