### ISSUE TITLE
imapnotify connecting but not triggering notifications

### ISSUE THREAD

**Issue by protist** [a-sk/node-imapnotify#5]
Hi, I've been using the latest version of imapnotify for a while now, installed from the AUR (0.1.0-6). However, it seems to have stopped working in the last few days. It appears to connect fine, but doesn't notify on new emails. I'm using the systemd service.

```
$ systemctl status --user imapnotify@main.js.service
● imapnotify@main.js.service - Execute scripts on new messages using IDLE imap command
   Loaded: loaded (/usr/lib/systemd/user/imapnotify@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2016-07-16 11:29:26 AEST; 5min ago
 Main PID: 11945 (node)
   CGroup: /user.slice/user-1000.slice/user@1000.service/imapnotify.slice/imapnotify@main.js.service
           └─11945 node /usr/bin/imapnotify -c /home/protist/.config/imapnotify/main.js

Jul 16 11:29:26 protist-XPS-17 systemd[596]: Started Execute scripts on new messages using IDLE imap command.
Jul 16 11:29:27 protist-XPS-17 imapnotify[11945]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":11945,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-07-16T01:29:27.026Z","v":0}
Jul 16 11:29:27 protist-XPS-17 imapnotify[11945]: {"name":"imap_inotify","hostname":"protist-XPS-17","pid":11945,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-07-16T01:29:27.028Z","v":0}
```

After a new email arrives on the server, nothing happens, and nothing changes in the status output.

OTOH, IMAP IDLE on my Android phone's K-9 app appears to be working fine with the same account. Is there a way to troubleshoot imapnotify further?

**Comment by a-sk** [comment]
Hi, can you start imapnotify process with DEBUG environment variable set, e.g:

``` sh
DEBUG=1 /usr/bin/imapnotify -c /home/protist/.config/imapnotify/main.js
```

May be there will be something interesting in the debug output.

**Comment by protist** [comment]
Nothing seems to happen. I disabled the systemd service, and started it manually as recommended.

```
$ DEBUG=1 /usr/bin/imapnotify -c ~/.config/imapnotify/main.js
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":6958,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-07-17T23:42:04.667Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":6958,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-07-17T23:42:04.668Z","v":0}
```

I sent myself an email. It was received with K-9's IDLE, but nothing was triggered with imapnotify.

**Comment by protist** [comment]
I did a bit more testing. I tested imapnotify with another email account from a different provider, and that worked fine.

However, I just tested the original "broken" email account with Thunderbird, and that worked fine with IDLE too. I'm confused as to what might have caused this problem, as imapnotify hasn't been updated in quite a while.

It looks like the AUR version of imapnotify has a single dependency on nodejs. I checked my pacman logs, and I upgraded this from 6.2.2-1 -> 6.3.0-1 on 2016-07-07. I tried reverting to the previous version of nodejs, then manually starting imapnotify again, but this didn't help. Prior to this, I upgraded nodejs from 6.2.1-1 -> 6.2.2-1 on 2016-06-18. I'm pretty sure I didn't notice the problem from this long ago, but I tried reverting anyway. This also made no difference.

**Comment by protist** [comment]
I just emailed my email provider, and they suggested that perhaps "Dovecot has been updated on the server side and the mail protocols have been updated". Is it possible that imapnotify only works with an older version of dovecot?

**Comment by a-sk** [comment]
It is possible.
Can you ask your provider to tell what version of Dovecot they are running now so I will be able to test it.

**Comment by protist** [comment]
They just replied. It's `dovecot-2.2.25-1.cp1158.x86_64`. They were unable to tell me the previous version.

**Comment by a-sk** [comment]
Thanks, I will try to reproduce the bug as soon as I have free time.

**Comment by protist** [comment]
Thank you, I appreciate it. Also, I'm happy to make you a temporary account on the email server I use, if you like. However, I'm not sure how useful this is, since I don't think I have access to any debugging logs from their end. I guess this will let you reproduce this issue at least.

**Comment by a-sk** [comment]
Oh, that would be great, thanks.

**Comment by protist** [comment]
I've emailed you the details. Thanks again for looking at this.

**Comment by protist** [comment]
Hello, I was just wondering if you have had time to look into this. Otherwise, I'll probably look into other alternatives. (I don't mean to sound rude; I just want my email to work again.) Cheers.

**Comment by a-sk** [comment]
Sorry, I haven't had a chance to look into this issue.
I do not use imapnotify myself anymore (I used email only for my work, and we switched to other tools).
I welcome you to look for alternatives, on my part, I will try to look into the issue in a week or two (it's interesting after all, why it does not work)

**Comment by protist** [comment]
No worries at all. I understand that it's no longer a high priority for you.

However, I could only find [two other programs](https://stackoverflow.com/questions/1307111/how-to-write-a-unix-script-that-gets-notified-with-imap-idle-from-gmail) that do similar things to imapnotify, and they will require me learning some basic perl or python. Since transitioning to another system will take a bit of work for me personally, I'm happy to wait a week or two and see what happens with imapnotify. Thanks again.

**Comment by a-sk** [comment]
Could you please email me temporary account details one more time, it seems like I've lost it.

**Comment by protist** [comment]
No worries; done. Thank you again for looking at this.

**Comment by a-sk** [comment]
I tested imapnotify with the config you gave me and it seems to work.
Can you test it once again on the temporary account and confirm it does not work.

``` js
{"name":"imap_inotify","hostname":"hostname","pid":56217,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-09-05T10:55:31.906Z","v":0}
{"name":"imap_inotify","hostname":"hostname","pid":56217,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-09-05T10:55:31.908Z","v":0}

{"name":"imap_inotify","hostname":"hostname","pid":56217,"level":30,"box":"INBOX","msg":"New mail","time":"2016-09-05T10:56:38.157Z","v":0}
{"name":"imap_inotify","hostname":"hostname","pid":56217,"level":20,"msg":"Found command: ls","time":"2016-09-05T10:56:38.161Z","v":0}
```

**Comment by protist** [comment]
This is very odd! I tested again, but it still doesn't work for me. I just get the same two initial lines.

```
$ DEBUG=1 /usr/bin/imapnotify -c ~/.config/imapnotify/test.js
{"name":"imap_inotify","hostname":"my_hostname","pid":22308,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-09-06T02:39:50.517Z","v":0}
{"name":"imap_inotify","hostname":"my_hostname","pid":22308,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-09-06T02:39:50.519Z","v":0}
```

I was trying to work out how our systems might differ, which might explain why it works for you and fails for me. I wasn't sure if you were using the same password manager, so I also tried hardcoding the password into the config file, with `exports.password = 'foo';`. This still failed.

I'm not sure what else might be different. Is nodejs the only dependency? I'm on version 6.5.0-1 now (in Arch Linux), although as above, I did try reverting to previous versions.

**Comment by a-sk** [comment]
Can you try to test from a different IP?

**Comment by protist** [comment]
I move my laptop between home and work, so I have already tested for my normal email accounts. I just tested again for this new test account, but it still doesn't work unfortunately.

**Comment by protist** [comment]
BTW what distro do you use? It might be another way to troubleshoot?

**Comment by a-sk** [comment]
I'm testing from mac os. I'll try to use docker to test from ubuntu.

**Comment by a-sk** [comment]
I tried from archlinux and node docker images, both times imapnotify worked.
Can you try to test it in `node` docker image.

**Comment by protist** [comment]
Sorry, I'm not familiar at all with docker. Could you please explain in more detail or show me a tutorial? I couldn't find anything clear on the web.

**Comment by protist** [comment]
Huh… that's odd. I installed imapnotify on my wife's computer, which also runs an up-to-date Arch Linux system. It works fine there! All relevant package versions would be the same, but the computer itself is different. I really don't know where else to find a difference between the two.

**Comment by protist** [comment]
FWIW I also set up a new user on my computer, that imapnotify fails for that user too.

**Comment by a-sk** [comment]
That's interesting, maybe you set up firewall rules, that somehow prevent impanotify to work correctly. Maybe try to disable it and test.

**Comment by protist** [comment]
Good idea, but unfortunately disabling my firewall made no difference.

**Comment by a-sk** [comment]
Ok, let's try to test in docker.
1. install docker [package](https://www.archlinux.org/packages/community/x86_64/docker/)
2. run `node` image `docker run -it node bash`
3. inside the container, clone node-imapnotify repo `git clone https://github.com/a-sk/node-imapnotify`
4. install npm deps: `cd node-imapnotify && npm i`
5. put imapnotify config file somewhere
6. run it: `node-imapnotify/bin/imapnotify -c absolute path to the config file`

**Comment by protist** [comment]
Just for posterity, in case I need to repeat it, here are the precise commands I had to use. And imapnotify didn't work, unfortunately. (See the last block for details.)

```
$ sudo pacman -S docker
$ sudo gpasswd -a ${USER} docker
```

Log in and out again.

```
$ sudo systemctl start docker
$ docker run -it node bash
root@11ba2a33fc1a:/# git clone https://github.com/a-sk/node-imapnotify
root@11ba2a33fc1a:/# cd node-imapnotify && npm i && cd ..
```

In the host system,

```
$ docker cp ~/.config/imapnotify/test.js 11ba2a33fc1a:/test.js
```

In the container,

```
root@11ba2a33fc1a:/# node-imapnotify/bin/imapnotify -c /test.js 
{"name":"imap_inotify","hostname":"11ba2a33fc1a","pid":46,"level":30,"box":"INBOX","msg":"Connected to server","time":"2016-09-07T10:39:37.349Z","v":0}
{"name":"imap_inotify","hostname":"11ba2a33fc1a","pid":46,"level":30,"box":"INBOX","msg":"Selecting box","time":"2016-09-07T10:39:37.354Z","v":0}
```

Send email to account and nothing changes.

**Comment by a-sk** [comment]
So, this is not your IP, not your environment, not your firewall, but it's definitely something on your computer.
Can your boot from a usb drive and try to test there.
I'm almost out of ideas ;(

**Comment by protist** [comment]
Ugh, I've spent an hour or so on this, but I'm having trouble, possibly due to corrupt USB sticks. This might be more complicated that envisaged.

I did try dual booting into my (K)ubuntu install, and imapnotify works perfectly well there. You did have it working in Arch though right? Was that just a "normal" install? I could also try installing Arch in virtualbox and testing there…

**Comment by protist** [comment]
This is really, really odd… I tested with Arch in Virtualbox (within my Arch host), and it works fine. However, when testing and previously in Kubuntu, I logged into the webmail of the test account, and sent an email to itself.

I tested again from the original Arch system that doesn't work, sending mail via webmail. Now it works! I tested again using my "normal" testing routine… mutt + msmtp. This time, imapnotify _didn't_ work again. So for some bizarre reason, on my normal system, imapnotify works if I send email through the same web interface, but not if I send it through mutt + msmtp + a different smtp server. I don't know how that can make a difference, since I've been confirming that the email is actually received in the box in all cases. Both situations should be the same.

(As an aside, when imapnotify worked on my wife's computer, it was using the "normal" test, i.e. mutt + msmtp. I also retested Arch-in-Arch Virtualbox, and this works with the "normal" test, too.)

Aaaaaaanndd… just to be thorough, I tested three more times with the original Arch system and webmail, and now it fails. But, it _did_ work at some stage on this system, so that shows it _is_ possible.

**Comment by a-sk** [comment]
Wow this is odd.

Can you test once again and try to sniff traffic using tcpdump,
something like `tcpdump -vv -l -A  'host $your_host'`
And for the test, change port to `143` and tls to `false` to see the text and not encrypted garbage.
If this fails and you don't see any traffic you can try to add iptables rule to log imap traffic.

**Comment by protist** [comment]
I made those changes in the imapnotify config, but it doesn't seem to want to connect now. These are the changes I made:

```
--- /home/protist/.config/imapnotify/test.js    2016-09-06 12:39:48.921828612 +1000
+++ /home/protist/.config/imapnotify/test.nocrypt.js    2016-09-09 21:40:35.325162334 +1000
@@ -6,8 +6,8 @@
 }

 exports.host = "FOO"
-exports.port = 993;
-exports.tls = true;
+exports.port = 143;
+exports.tls = false;
 exports.tlsOptions = { "rejectUnauthorized": true };
 exports.username = "foo@bar.com";
 exports.password = 'baz';
```

And now it won't run.

```
$ imapnotify -c ~/.config/imapnotify/test.nocrypt.js
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T11:40:47.230Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"{ Error: 140016355358528:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T11:40:47.246Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2016-09-09T11:40:47.247Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T11:40:47.418Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"{ Error: 140016355358528:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T11:40:47.420Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":30,"box":"INBOX","msg":"Scheduling restart in 3000","time":"2016-09-09T11:40:47.420Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T11:40:50.548Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"{ Error: 140016355358528:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T11:40:50.548Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":30,"box":"INBOX","msg":"Scheduling restart in 6000","time":"2016-09-09T11:40:50.548Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T11:40:56.676Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":23430,"level":50,"box":"INBOX","msg":"{ Error: 140016355358528:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T11:40:56.676Z","v":0}
/usr/lib/node_modules/imapnotify/bin/imapnotify:83
        throw Error('Max retry limit reached')
        ^

Error: Max retry limit reached
    at Error (native)
    at Connection.<anonymous> (/usr/lib/node_modules/imapnotify/bin/imapnotify:83:15)
    at Connection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TLSSocket._onError (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:150:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by a-sk** [comment]
I answered to the email address you sent me test account details from.

**Comment by protist** [comment]
That new config still won't connect for me. I wonder if that is informative?

Just to make sure that there was no copy-paste error, I modified your new `test.json` config, reverting the port back to 993 and enabling tls. This connects fine (although I didn't test the notify part), so presumably we're using the same file. Using the unmodified config file results in the following errors, similar to before.

```
$ imapnotify -c ~/.config/imapnotify/test.nocrypt.json
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T23:18:27.809Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"{ Error: 139938010396480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T23:18:27.826Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":30,"box":"INBOX","msg":"Restarting immediately","time":"2016-09-09T23:18:27.827Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T23:18:27.945Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"{ Error: 139938010396480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T23:18:27.946Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":30,"box":"INBOX","msg":"Scheduling restart in 3000","time":"2016-09-09T23:18:27.946Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T23:18:31.066Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"{ Error: 139938010396480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T23:18:31.067Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":30,"box":"INBOX","msg":"Scheduling restart in 6000","time":"2016-09-09T23:18:31.067Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":30,"box":"INBOX","msg":"Connection ended","time":"2016-09-09T23:18:31.071Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"Error registered","time":"2016-09-09T23:18:31.191Z","v":0}
{"name":"imap_inotify","hostname":"protist-XPS-17","pid":5204,"level":50,"box":"INBOX","msg":"{ Error: 139938010396480:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:\n\n    at Error (native)\n    at Socket.ondata (_stream_wrap.js:58:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:543:20) source: 'socket' }","time":"2016-09-09T23:18:31.192Z","v":0}
/usr/lib/node_modules/imapnotify/bin/imapnotify:83
        throw Error('Max retry limit reached')
        ^

Error: Max retry limit reached
    at Error (native)
    at Connection.<anonymous> (/usr/lib/node_modules/imapnotify/bin/imapnotify:83:15)
    at Connection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TLSSocket._onError (/usr/lib/node_modules/imapnotify/node_modules/imap/lib/Connection.js:150:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by a-sk** [comment]
Oh, please, try the latest version from git.
It seems like you could not turn off tls in the older versions: #6

**Comment by protist** [comment]
Well, the latest version from git works perfectly! I've tested half a dozen times, and it's extremely reliable. I guess I should have tested the git version earlier. Having said that, while testing, I installed the _stable_ release on my wife's computer, which worked. The stable release had also worked fine for me for quite a while, before breaking for some (still unknown) reason. Thanks for all the help, and sorry for all the trouble!

(I tried to work out which commit the [stable AUR release](https://aur.archlinux.org/packages/nodejs-imapnotify/) referred to, which was [0.1.0](http://registry.npmjs.org/imapnotify/-/imapnotify-0.1.0.tgz), but it wasn't clear to me. Perhaps you could also push the latest git version as the stable release?)

**Comment by a-sk** [comment]
Yaaahoo! I'm glad that it's finally working for you.
I'm no longer the maintainer of the AUR package, but I marked it as out of date package and hope it will be updated soon.
